language: java

jdk:
  - oraclejdk8

script: 
  - mvn clean test
  - mvn clean test -Pintegration-test
  #- mvn clean test -Pperformance-test

# whitelist
branches:
 only:
   - master
  
notifications:
  slack: larus-ba:otcexf1c5NioYQEIG8uK1HaY
